[template]
src   = "maxscale.cnf"
dest  = "/etc/maxscale.cnf"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/database/credentials/adminUser",
  "/database/credentials/adminPass",
  "/database/cluster/mysqlNodes"
]
check_cmd = "/app/bin/check {{ .src }}"
reload_cmd = "maxadmin -pmariadb reload config"
