[template]
src   = "maxscale.cnf"
dest  = "/etc/maxscale.cnf"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/services/database_port"
]
check_cmd = "/app/bin/check {{ .src }}"
reload_cmd = "maxadmin -pmariadb reload config"
